apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'my-app'
  namespace: '{{ meta.namespace }}'
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
      containers:
        ....